-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 19:58:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Porklogic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Porklogic` ;

-- -----------------------------------------------------
-- Schema Porklogic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Porklogic` DEFAULT CHARACTER SET utf8 ;
USE `Porklogic` ;

-- -----------------------------------------------------
-- Table `Porklogic`.`Baconbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Porklogic`.`Baconbit` (
  `Id` INT NOT NULL,
  `Baconbit ID` INT NULL,
  `Client` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `Hardware Version` INT NULL,
  `Firmware Version` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Porklogic`.`Baconbit`
-- -----------------------------------------------------
START TRANSACTION;
USE `Porklogic`;
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (1, 1497, 'Mary Ann Brewer', 'Qatar ', 'Delivered', 'Augue lorem bibendum', 2300, 2463);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (2, 2753, 'Carmen Ramirez', 'Netherlands', 'Pending', 'Bibendum sed commodo', 3874, 2668);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (3, 4685, 'Tom Ford', 'Ukraine', 'Pending', 'Magna amet', 3018, 2109);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (4, 4889, 'Christine Gordon', 'Colombia', 'Delivered', 'Elit Est', 2068, 4298);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (5, 2663, 'Beatrice Wade', 'Armenia', 'Delivered', 'Odio condimentum', 4094, 785);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (6, 152, 'Joe Hoffman', 'Gambia', 'Delivered', 'Purus dictum laoreet', 2128, 2098);
INSERT INTO `Porklogic`.`Baconbit` (`Id`, `Baconbit ID`, `Client`, `Location`, `Status`, `Manufacturer`, `Hardware Version`, `Firmware Version`) VALUES (7, 371, 'Jose Hughes', 'China', 'Delivered', 'Dictum suscipit', 2128, 94);

COMMIT;

